### ISSUE TITLE
Title.tmd not found?

### ISSUE THREAD

**Issue by cgf229** [DS-Homebrew/hiyaCFW#10]
can anyone tell me how to fix this

**Comment by RocketRobz** [comment]
Re-run the HiyaCFW Helper.

**Comment by cgf229** [comment]
ok?

**Comment by RocketRobz** [comment]
You mean you never used it?

**Comment by cgf229** [comment]
no I did and I did it again and it is still not working am I supposed to move it to the root of the sd

**Comment by cgf229** [comment]
it has the error has occurred message

**Comment by RocketRobz** [comment]
Fill the SD card so there's 2GB or less left.

**Comment by cgf229** [comment]
no it's error 1-2435-8325
