### ISSUE TITLE
Do you now support SD cards above 4G?

### ISSUE THREAD

**Issue by Dsseed** [DS-Homebrew/hiyaCFW#12]
For this reason, it has not been installed hiyaCFW

I do n’t know if I support it now

**Comment by StaticSaga** [comment]
Yes, they are supported, but the System Launcher has a signed 32-bit counter for **free** space, therefore it wraps around to negative numbers in the 2GB-4GB (and 6-8 and so on) interval.
The workaround is filling the SD (it can be whatever you want, music, videos, dummy files...) until you have a supported amount of free space.
See [the DSi CFW FAQ](https://dsi.cfw.guide/faq#why-do-i-boot-into-an-error-has-occurred-when-i-use-hiyacfw-with-the-default-dsi-menu-and-how-can-i-fix-it) for a detailed explanation, for a free space checker and for a small guide about dummy files.
