### ISSUE TITLE
include the packgage CID and nand binaries from other package. Missing TWL9crypto.bin as well.

### ISSUE THREAD

**Issue by Elohimuel** [DS-Homebrew/hiyaCFW#13]
The statement says it all as the information relating to proper boot and setup of console
As relating to hiya custom firmware helper. Proper install of the boot 9 binaries as related to
God mode 9 and DSI to 3ds setup. - (basically what one should do is put these in the bootloader setup folder.)

**Comment by Peter0x44** [comment]
I really don't understand what is meant here -- hiyaCFW simply doesn't work on the 3ds at all
