### ISSUE TITLE
GTA: Chinatown Wars Black Screen Before Picking Save File

### ISSUE THREAD

**Issue by FreeUnblockedGames** [DS-Homebrew/hiyaCFW#15]
It only happens when I launch the game using HiyaCFW forwarder (not sure if this is a edo3900 Forwarder Maker Problem), but it works fine when I launch it using twilight menu ++.

**Comment by RocketRobz** [comment]
This is an issue with the forwarder maker.

**Comment by FreeUnblockedGames** [comment]
Okay Thanks
