### ISSUE TITLE
Has the pokemon soulsilver/heartgold freezing ever been fixed?

### ISSUE THREAD

**Issue by k00lk4t** [DS-Homebrew/hiyaCFW#26]
So I started pokemon soulsilver 2 days ago and from the first 15 minutes of playing i froze. I dont want to accidentally lose progress anymore as ive already froze 4-5 times. Ive tried everything i could find about. I tried every kind of diffrent rom, even the anti piracy patch but im still freezing.

**Comment by Dark98** [comment]
Try playing with the "no$ fix" cheat enabled?
Edit: also this is related to nds-bootstrap not HiyaCFW

**Comment by lifehackerhansol** [comment]
Also, it's a duplicate of https://github.com/DS-Homebrew/nds-bootstrap/issues/737

**Comment by k00lk4t** [comment]
> Try playing with the "no$ fix" cheat enabled?
> Edit: also this is related to nds-bootstrap not HiyaCFW

Sorry, i couldnt find the nds bootstrap repository. How do i use cheats in nds bootstrap?

**Comment by Dark98** [comment]
> > Try playing with the "no$ fix" cheat enabled?
> > Edit: also this is related to nds-bootstrap not HiyaCFW
> 
> Sorry, i couldnt find the nds bootstrap repository. How do i use cheats in nds bootstrap?

There's a section in the FAQ here that explains setting them up, then once you've got the cheatdb in place press "X" then "Y" while on the icon of the game
https://wiki.ds-homebrew.com/twilightmenu/faq

**Comment by k00lk4t** [comment]
> Try playing with the "no$ fix" cheat enabled?
> Edit: also this is related to nds-bootstrap not HiyaCFW

i figured how to add cheats (even though i might have had to deleted 4.5 hours of progress to do it) but i have one least question. Do I only enable no$gba fix or do i need to enable the anti piracy patch? If i enable both the screen just turns white when i launch the game.

**Comment by Dark98** [comment]
You shouldn't of had to delete any progress to add the cheats, also only enable the no$gba fix

Any further replies please bring to https://github.com/DS-Homebrew/nds-bootstrap/issues/737

**Comment by k00lk4t** [comment]
Oh yeah i fixed the problem, i just enabled no$gba fix and i played 4 more hours. Thank you for all of your help!
