### ISSUE TITLE
Update fix_ndsheader.py to use a current version of Python

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/hiyaCFW#32]
[fix_ndsheader.py](https://github.com/DS-Homebrew/hiyaCFW/blob/unlaunch/fix_ndsheader.py) currently requires python2. It would be nice to have this updated to Python 3 or so.

The version of this script that TWiLight Menu++ uses does use python3, but it seems to have some issues as hiyaCFW won't load when using it (white screens after the splash), unless I just set it up wrong.

**Comment by NightScript370** [comment]
There were changes made to that file for adapting to TWiLight's usecase beyond just a simple Python 3 upgrade.
I believe the same thing applies here.

The best way to upgrade would be to go through the code side-by side and see which areas aren't just syntax differences.
