### ISSUE TITLE
Add SD writelock detection 

### ISSUE THREAD

**Issue by skunkmommy** [DS-Homebrew/hiyaCFW#36]
I use HiyaCFW on a nightly basis for Sleep Clock, as it's an easy and cheap way to track sleep using just a DSi.
However, I always have to make sure the write protect notch is up. If it isn't, my tracked sleep doesn't save.
I would prefer if the app tested for write protection on startup, and prompted the user to disable it if the check fails.

**Comment by Masamune3210** [comment]
The system does not have a concept of if the slider is in a certain position as far as I know, only if it can successfully write to the card or not. Multiple things can cause a write to fail, not just the card being write-protected. 

Also, how many times are you taking the card in and out lol. I wouldn't do it too much, you can actually wear out the slot if you exercise it too much, the reader is only rated for a certain amount of insertions

**Comment by skunkmommy** [comment]
> The system does not have a concept of if the slider is in a certain position as far as I know, only if it can successfully write to the card or not. Multiple things can cause a write to fail, not just the card being write-protected.
> 
> Also, how many times are you taking the card in and out lol. I wouldn't do it too much, you can actually wear out the slot if you exercise it too much, the reader is only rated for a certain amount of insertions

I think twilightmenu++ has stuff in place for this already, maybe have a look at how it's done there? Also, this should be an option for those who regularly need to remove their card or have an SD with a loose, but still working notch. The message shown if it fails could prompt the user to check if the notch is loose and check the SD slot for anything weird etc.

**Comment by NightScript370** [comment]
> I think twilightmenu++ has stuff in place for this already, maybe have a look at how it's done there?

No it doesn't

**Comment by Masamune3210** [comment]
Its not that something doesnt or does have code to work with this, its just fundamentally something not exposed to the system. As far as I know, the controller doesn't have multiple states for if a write failed or not really, so much as it likely just either does the command successfully....or it doesn't and returns a error to the system

**Comment by RocketRobz** [comment]
> > I think twilightmenu++ has stuff in place for this already, maybe have a look at how it's done there?
> 
> No it doesn't

TWiLight Menu++ displays a message if the SD is found to be write-locked, and prevents the user from going further.
