### ISSUE TITLE
I have no clue whatsoever on how to update to this latest version

### ISSUE THREAD

**Issue by 44cK3r** [DS-Homebrew/hiyaCFW#37]
Can you pretty please guide me on exactly how to do it as I just finished trying to do it but when I finished following the guide I realised it never once said to extract the: hiyaCFW.7z so I don't think I did it right my DSixl still works though thankfully

**Comment by RocketRobz** [comment]
You need to re-run the hiyaCFW Helper in order to properly update.
Before doing so, backup the `title` folder on the SD root, and then after the helper has been re-ran, restore the `title` folder.

**Comment by 44cK3r** [comment]
Does that mean the tool downloads the latest update automatically

**Comment by RocketRobz** [comment]
> Does that mean the tool downloads the latest update automatically

Yes, it does.

**Comment by 44cK3r** [comment]
Oh few thank god for that I think I successfully updated then thank you so very much I also hope this project never goes away as I absolutely love my DSixl thank you so very much for the many many years of support of this masterpiece (sorry I'm not very good at English very sorry if I didn't word anything right hopefully you know what I mean)
