### ISSUE TITLE
Flipnote studio white screen

### ISSUE THREAD

**Issue by MrButterfingersss** [DS-Homebrew/hiyaCFW#39]
My issue is that when trying to start flipnote studio I get a white screen. But when I use unlaunch and go normal boot (non cfw) it works fine this only happen while using CFW. I used stylehax to install hiyaCFW and when booting TWIlightmenu it works fine.

**Comment by RocketRobz** [comment]
Which region is Flipnote, and which region is your CFW?

**Comment by MrButterfingersss** [comment]
USA and USA I believe.

**Comment by RocketRobz** [comment]
> USA and USA I believe.

Is the CFW region the original one, or the newly set one? If it's the newly set one, then what's the original region?

**Comment by MrButterfingersss** [comment]
Newly set JPN was the original. Tho this wasn't a problem for a while.

**Comment by RocketRobz** [comment]
> Newly set JPN was the original. Tho this wasn't a problem for a while.

idk then. Try creating a forwarder for Flipnote then.
https://wiki.ds-homebrew.com/ds-index/forwarders
After creating the forwarder, launch it, then hold the Y button to open the per-game settings menu, and set the region to USA.

**Comment by MrButterfingersss** [comment]
Alright ill try that.

**Comment by MrButterfingersss** [comment]
Ok so something weird happened. it went to the menu for flipnote studio then it just crashed. and now there's a white screen again (yes i set it to usa)

**Comment by MrButterfingersss** [comment]
Also now there's 2 flipnote studios.

**Comment by MrButterfingersss** [comment]
i fixed it

**Comment by MrButterfingersss** [comment]
I made it run in dsi mode and set it to English

**Comment by RocketRobz** [comment]
> I made it run in dsi mode and set it to English

DSi mode is already used by default for DSiWare, but nice!
