### ISSUE TITLE
Apps can not access touch screen through hiyacfw when boot on iQue console

### ISSUE THREAD

**Issue by R-YaTian** [DS-Homebrew/hiyaCFW#9]
Touch screen does not  work on all system apps and dsiware except TWiLightMenuPP and the System Menu.

**Comment by RocketRobz** [comment]
Is the console Japanese, by any chance?

**Comment by ApacheThunder** [comment]
I assume all "iQue" consoles are Chinease units? iQue was a China only thing I recall.

**Comment by R-YaTian** [comment]
> Is the console Japanese, by any chance?

It's Chinese iQue console. I think hiyacfw seems to made some incorrect changes to the sys hardware configuration. After I boot the hiyacfw, the touch screen does not work normally. Even if I shut the console and press A+B then use unlaunch to load Dsiware, the touch screen will not work properly also. This problem will continue until I start DS Download Play/Pictochat that based on DS unit. (Note that the Apps may not be able to get the correct XY coordinate, because touch the screen will get a reaction) BTW, the touch screen on System Menu and the TWiLightMenuPP always works fine through hiyacfw. But when using hiyacfw to boot TWiLightMenuPP and load a retail game, the touch screen does not works fine on the games. Sry for my English.

**Comment by R-YaTian** [comment]
> I assume all "iQue" consoles are Chinease units? iQue was a China only thing I recall.

Oh, yes.

**Comment by R-YaTian** [comment]
Fixed via a new ips patch for CHN launcher
